version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always

  celery:
    build:
      context: .
    env_file:
      - .env
    command: celery -A src.utils.celery_worker worker --loglevel=info
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    depends_on:
      - redis
    environment:
      - TZ=Europe/Kyiv
  
  beat:
    build: .
    env_file:
      - .env
    command: celery -A src.utils.celery_worker beat --loglevel=info
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    depends_on:
      - redis
      - celery

  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery
