version: "3.3"

services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

  celery:
    build:
      context: .
    env_file:
      - .env
    command: celery -A src.utils.celery_worker worker --loglevel=info
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    depends_on:
      - redis
      # - db
    environment:
      - TZ=UTC
  
  beat:
    build: .
    env_file:
      - .env
    command: celery -A src.utils.celery_worker beat --loglevel=info
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    depends_on:
      - redis
      - celery

  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/fastapi_app
      - ./tmp:/fastapi_app/tmp
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      # - db
      - redis
      - celery

# volumes:
#   postgres_data:
