"""Add payout

Revision ID: 8f9ad81647d4
Revises: 0d8f871e4a8d
Create Date: 2025-07-14 03:55:51.650686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9ad81647d4'
down_revision: Union[str, Sequence[str], None] = '0d8f871e4a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.Enum('TikTok', 'Wildberries', 'Other', name='location_enum'), nullable=False),
    sa.Column('role_type', sa.Enum('EMPLOYEE', 'MANAGER', 'ADMIN', name='roletype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts')
    # ### end Alembic commands ###
