"""Cash on hand

Revision ID: 6dc6b4664a62
Revises: dee32b7212ee
Create Date: 2025-08-16 15:23:54.904079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc6b4664a62'
down_revision: Union[str, Sequence[str], None] = 'dee32b7212ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shift_records', sa.Column('cash_on_hand', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shift_records', 'cash_on_hand')
    # ### end Alembic commands ###
