"""Shifts store update

Revision ID: 5ce92435e616
Revises: d32dc26a4413
Create Date: 2025-08-21 21:05:12.681501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ce92435e616'
down_revision: Union[str, Sequence[str], None] = 'd32dc26a4413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shift_records', sa.Column('changed_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('promotion', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('to_store', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('refund', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('service', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('receipt', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('store_shift_records', sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shift_records', 'comments')
    op.drop_column('store_shift_records', 'receipt')
    op.drop_column('store_shift_records', 'service')
    op.drop_column('store_shift_records', 'refund')
    op.drop_column('store_shift_records', 'to_store')
    op.drop_column('store_shift_records', 'promotion')
    op.drop_column('store_shift_records', 'discount')
    op.drop_column('store_shift_records', 'changed_price')
    # ### end Alembic commands ###
