"""Add cafe

Revision ID: 2eafc0800306
Revises: 5b766fc035ff
Create Date: 2025-07-19 20:19:15.270738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eafc0800306'
down_revision: Union[str, Sequence[str], None] = '5b766fc035ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coffee_shift_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('terminal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('barista_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['coffee_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffee_shift_records')
    op.drop_table('coffee_shops')
    # ### end Alembic commands ###
