"""add shifts date unique

Revision ID: cf2cf12bc9aa
Revises: 923966a65665
Create Date: 2025-07-14 02:55:53.873984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2cf12bc9aa'
down_revision: Union[str, Sequence[str], None] = '923966a65665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shifts', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='unique')
    # ### end Alembic commands ###
