"""Ordertype settings

Revision ID: 439d7d0d253e
Revises: 32725b23b9d6
Create Date: 2025-12-28 22:28:36.458388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439d7d0d253e'
down_revision: Union[str, Sequence[str], None] = '32725b23b9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_order_type_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_type_id', sa.Integer(), nullable=False),
    sa.Column('custom_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_order_type_settings_id'), 'user_order_type_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_order_type_settings_order_type_id'), 'user_order_type_settings', ['order_type_id'], unique=False)
    op.create_index(op.f('ix_user_order_type_settings_user_id'), 'user_order_type_settings', ['user_id'], unique=False)
    op.add_column('order_types', sa.Column('default_employee_percent', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_types', 'default_employee_percent')
    op.drop_index(op.f('ix_user_order_type_settings_user_id'), table_name='user_order_type_settings')
    op.drop_index(op.f('ix_user_order_type_settings_order_type_id'), table_name='user_order_type_settings')
    op.drop_index(op.f('ix_user_order_type_settings_id'), table_name='user_order_type_settings')
    op.drop_table('user_order_type_settings')
    # ### end Alembic commands ###
