"""Create Many-Many Order Ordertypes

Revision ID: 43ff68089c63
Revises: 040f0b9e005a
Create Date: 2025-11-30 17:02:50.723280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ff68089c63'
down_revision: Union[str, Sequence[str], None] = '040f0b9e005a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_order_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_type_id'], ['order_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'order_type_id', name='uq_order_type_per_order')
    )
    op.create_index(op.f('ix_order_order_types_id'), 'order_order_types', ['id'], unique=False)
    op.create_index(op.f('ix_order_order_types_order_id'), 'order_order_types', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_order_types_order_type_id'), 'order_order_types', ['order_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_types_order_type_id'), table_name='order_order_types')
    op.drop_index(op.f('ix_order_order_types_order_id'), table_name='order_order_types')
    op.drop_index(op.f('ix_order_order_types_id'), table_name='order_order_types')
    op.drop_table('order_order_types')
    # ### end Alembic commands ###
