"""Shift date payment

Revision ID: d32dc26a4413
Revises: ed55a2a5f8b6
Create Date: 2025-08-21 02:06:16.290651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32dc26a4413'
down_revision: Union[str, Sequence[str], None] = 'ed55a2a5f8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_assignments', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('shift_assignments', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('shift_assignments', sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('shift_start', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('shift_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shift_end')
    op.drop_column('users', 'shift_start')
    op.drop_column('shift_assignments', 'salary')
    op.drop_column('shift_assignments', 'end_time')
    op.drop_column('shift_assignments', 'start_time')
    # ### end Alembic commands ###
