"""Add creation date

Revision ID: a3d34f813850
Revises: 8f9ad81647d4
Create Date: 2025-07-14 14:18:04.820451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d34f813850'
down_revision: Union[str, Sequence[str], None] = '8f9ad81647d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('payouts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('returnings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('shift_assignments', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('shifts', sa.Column('created_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'created_at')
    op.drop_column('shift_assignments', 'created_at')
    op.drop_column('returnings', 'created_at')
    op.drop_column('payouts', 'created_at')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
