"""fines

Revision ID: 040f0b9e005a
Revises: f35060880576
Create Date: 2025-11-29 11:50:17.729443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '040f0b9e005a'
down_revision: Union[str, Sequence[str], None] = 'f35060880576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_order_types_id'), 'order_types', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'SUCCESS', 'ERROR', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('related_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'order_types', ['type_id'], ['id'])
    op.add_column('returnings', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('returnings', sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('returnings', sa.Column('penalty_distribution', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_foreign_key(None, 'returnings', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'returnings', type_='foreignkey')
    op.drop_column('returnings', 'penalty_distribution')
    op.drop_column('returnings', 'penalty_amount')
    op.drop_column('returnings', 'order_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'type_id')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_order_types_id'), table_name='order_types')
    op.drop_table('order_types')
    # ### end Alembic commands ###
