"""Stores_employee

Revision ID: dee32b7212ee
Revises: ba1a0fed90c5
Create Date: 2025-08-16 02:11:13.838304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee32b7212ee'
down_revision: Union[str, Sequence[str], None] = 'ba1a0fed90c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shift_employees', sa.Column('is_warehouse', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shift_employees', 'is_warehouse')
    # ### end Alembic commands ###
