"""User can_take_vacation

Revision ID: 775124ea0d08
Revises: d3d04517e8e4
Create Date: 2025-08-22 16:37:20.286397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775124ea0d08'
down_revision: Union[str, Sequence[str], None] = 'd3d04517e8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_take_vacation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_take_vacation')
    # ### end Alembic commands ###
