"""Add COFFEE to userrole enum

Revision ID: c990b47f1747
Revises: 2eafc0800306
Create Date: 2025-07-19 20:39:30.334784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c990b47f1747'
down_revision: Union[str, Sequence[str], None] = '2eafc0800306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'COFFEE'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
