"""Indexes

Revision ID: ed55a2a5f8b6
Revises: 6dc6b4664a62
Create Date: 2025-08-21 01:15:44.728754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed55a2a5f8b6'
down_revision: Union[str, Sequence[str], None] = '6dc6b4664a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_date_created_by', 'orders', ['date', 'created_by'], unique=False)
    op.create_index('ix_payouts_date_user_id', 'payouts', ['date', 'user_id'], unique=False)
    op.create_index('ix_returnings_date', 'returnings', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_returnings_date', table_name='returnings')
    op.drop_index('ix_payouts_date_user_id', table_name='payouts')
    op.drop_index('ix_orders_date_created_by', table_name='orders')
    # ### end Alembic commands ###
