"""Store expences

Revision ID: f35060880576
Revises: caa04f7d1c72
Create Date: 2025-08-29 14:42:53.633689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35060880576'
down_revision: Union[str, Sequence[str], None] = 'caa04f7d1c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shift_records', sa.Column('expenses', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shift_records', 'expenses')
    # ### end Alembic commands ###
