"""include_in_employee_salary

Revision ID: 45de876a5b21
Revises: 439d7d0d253e
Create Date: 2025-12-29 15:59:20.288508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45de876a5b21'
down_revision: Union[str, Sequence[str], None] = '439d7d0d253e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_types', sa.Column('include_in_employee_salary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_types', 'include_in_employee_salary')
    # ### end Alembic commands ###
