"""Shifts store time

Revision ID: caa04f7d1c72
Revises: 775124ea0d08
Create Date: 2025-08-24 14:40:19.891186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa04f7d1c72'
down_revision: Union[str, Sequence[str], None] = '775124ea0d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shift_employees', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('store_shift_employees', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('store_shift_employees', sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shift_employees', 'salary')
    op.drop_column('store_shift_employees', 'end_time')
    op.drop_column('store_shift_employees', 'start_time')
    # ### end Alembic commands ###
